cache:
  paths:
  - node_modules

stages:
- install
- lint
- build
- deploy to gitlab

install:
  stage: install
  script:
  - yarn
  - git status
  - git checkout .
  - git status

lint:
  stage: lint
  script:
  - yarn lint:markdown

build:
  stage: build
  script:
    - yarn prod
    - ls
  artifacts:
    name: "CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - public

deploy to gitlab:
  stage: deploy to gitlab
  script:
    - rm -rf /etc/gitlab-runner/blog && mkdir /etc/gitlab-runner/blog
    - cp -r public/* /etc/gitlab-runner/blog
    - echo '部署到gitlab上成功'
  dependencies:
    - build
  environment:
    name: gitlab
    url: http://120.79.62.126
    on_stop: stop deploy on gitlab

stop deploy on gitlab:
  stage: deploy to gitlab
  script: rm -rf /etc/gitlab-runner/blog
  when: manual
  environment:
    name: gitlab
    action: stop